server :
  port : 8081
Spring:
  kafka :
    boostrap-servers : localhost:9092
    consumer :
      group-id : "my-awesome-app"

  mail :
    host : smtp.gmail.com
    port : 587
    username : phongsawattest99
    password : moowfnjkfzkpueah
    properties :
      mail :
        smtp :
          auth : true
          starttls :
            enable : true

app:
  token:
    secret : m#MySecretGGWP2024
    issuer : BackendService
  email :
    from : phongsawattest99@gmail.com